name: 'Install Poetry Action'
author: 'Michael Ellis'
description: |
    'Installs Poetry via pip and project dependencies including testing group'
inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.10'
  poetry-version:
    description: 'Poetry version to install'
    required: false
    default: '2.0.0'
  dependency-group:
    description: 'Dependency group to install'
    required: false
    default: 'testing'

runs:
  using: "composite"
  steps:
    - name: Install Poetry via pip
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install "poetry==${{ inputs.poetry-version }}"
        poetry --version
    
    - name: Configure Poetry
      shell: bash
      run: |
        # Make poetry create the virtualenv in the project directory
        poetry config virtualenvs.in-project true
    
    - name: Install Dependencies for Specified Groups
      shell: bash
      run: |
        echo "Installing dependency groups: ${{ inputs.dependency-group }}"
        
        # Install dependencies for specified groups
        poetry install --no-interaction --only ${{ inputs.dependency-group }}
        
        # Verify installation
        poetry show --tree